% !TEX TS-program = pdflatexmk
\documentclass[a4paper,11pt]{article}

\usepackage{Temp_short}
\usepackage[bottom]{footmisc}
\usepackage{commath}
\setlength{\jot}{0.3cm}
\allowdisplaybreaks[2]

\newenvironment{Ncenter}{%
  \setlength\topsep{-10pt}
  \setlength\parskip{-100pt}
  \begin{center}
}{%
  \end{center}
}

\bibliographystyle{abbrv}

\newcommand{\kmo}{k_{\mathrm{OT \to O+T}}}
\newcommand{\kOpT}{k_{\mathrm{O+T \to OT}}}
\newcommand{\kmt}{k_{\mathrm{OTE \to OT+E}}}
\newcommand{\kt}{k_{\mathrm{OT+E \to OTE}}}
\newcommand{\kc}{k_{\mathrm{OT+E \to OTE}}}
\newcommand{\kE}{k_{\mathrm{OTE \to OCE}}}
\newcommand{\kD}{k_{\mathrm{OC \to O+C}}}
\newcommand{\vp}{v_{\mathrm{prod}}}
\newcommand{\vd}{k_{\mathrm{T \to \emptyset}}}
\newcommand{\Trel}{T_{\rm{rel}}}
\newcommand{\EC}{EC_{\rm{50}}}
\newcommand{\kdOT}{K_{\mathrm{dOT}}}
\newcommand{\Trelmin}{T_{\rm{rel,min}}}

\makeatletter 
\renewcommand{\thefigure}{S\@arabic\c@figure}
\renewcommand{\thesection}{S\@arabic\c@section}
\renewcommand{\thetable}{S\@arabic\c@table}
\addto\captionsenglish{\renewcommand{\figurename}{Supplementary Figure}}
\addto\captionsenglish{\renewcommand{\tablename}{Supplementary Table}}

\title{Supplementary File S1 for Pedersen et al. (2013)}
\author{Lykke Pedersen, \and Peter H Hagedorn, \and Marie Lindholm, \and Morten Lindow}
\date{}

\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle

This document is the supplementary file for the manuscript entitled ``A kinetic model of enzyme recruiting oligonucleotides predicts an optimal affinity and explains why shorter and less affine oligonucleotides may be more potent" (2013) and it is a vignette for the R-package ASOmodel.

The functions and data used to produce the figures in the main manuscript and this supplementary file are available after installing and the ASOmodel package in R
<<>>=
require(devtools)
install_github('ASOmodel',username='lykkep')
require(ASOmodels)
@
The ASOmodels package contains the following functions:
\begin{enumerate}
\item \texttt{Trel}
\item \texttt{TrelNO}
\item \texttt{Trelstoc}
\item \texttt{plot.doseresponse}
\item \texttt{EC50}
\item \texttt{EC50NO}
\item \texttt{EC50stoc}
\item \texttt{diffASO}
\item \texttt{pretty10expLP}
\end{enumerate}

\newpage

\tableofcontents

\newpage


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{The rate-equations of the ASO model}
The kinetic ASO model governs seven ODEs for the seven variables: free target ($T$), free oligonucleotide ($O$), free RNAse H ($E$), complex of oligonucleotide and target ($OT$), complex of oligonucleotide, target and RNAse H  ($OTE$), complex of cleaved target, oligonucleotide and RNase H ($OCE$), and complex of cleaved target and oligonucleotide  ($OC$).
\begin{align}
%T
\frac{\dif [T]}{\dif t} &= \vp - \vd [T]-k_{O+T \to OT} [T] [O] +k_{OT\to O+T } [OT] \\
%OT
\frac{\dif [OT]}{\dif t} &= \ko[O][T]-\kmo[OT] \nonumber \\
	& \quad -\kt[OT][E]+\kmt [OTE]-\vd[OT] \\
%OTE
\frac{\dif [OTE]}{\dif t} &= \kt[E][OT]-\kmt[OTE] \nonumber \\
	& \quad -(\vd+\kE)[OTE]\\
%E
\frac{\dif [E]}{\dif t} &= -\kt[E][OT]+\kmt([OTE]+[OCE]) \nonumber \\
	& \quad+\vd[OTE]\\
%O
\frac{\dif [O]}{\dif t}&= \kmo [OT]-\ko[O][T] +\kD [OC]+\vd([OT]+[OTE])  \\
%ODE
\frac{\dif [OCE]}{\dif t}& = \kE [OTE]-\kmt [OCE]\\
%OD
\frac{\dif [OC]}{\dif t}& = \kmt [OCE]-\kD [OC]
\end{align}
Complex formation and breaking are denoted by rate constants $k$ with subscripts. The target production rate is denoted by $\vp$ and the degradation rate by $\vd$, respectively.

Steady-state is reached when the Eqs.~(1)-(7) are equated to zero. Using Maple16 the steady-state concentrations are found. They all depend on the roots to a fourth order polynomial with coefficients calculated within the R-function \texttt{Trel()}. The one root that ensures that all concentrations are non-negative and also fullfills that
\begin{align*}
 &[O]+[OTE]+[OT]+[OCE]+[OC] = O_t \quad \mathrm{and}\\ 
 &[OTE]+[OCE]+[E] = E_t \enspace,
\end{align*}
is chosen. 

%Trel
When there is no oligonucleotide added to the system, the steady-state concentration of target is $[T]=\frac{\vp}{ \vd}$. When oligonucleotide is added to the system, the total concentration of target at steady-state is the sum of the concentrations $[T]$, $[OT]$ and $[OTE]$. The relative total target concentration at steady-state is then calculated as 
\begin{equation}
\Trel = \frac{[T]+[OT]+[OTE]}{\frac{\vp}{ \vd}} \enspace.
\end{equation}

%EC50
The half maximal effect concentration ($\EC$) is the concentration of total nucleotide needed to reduce the target concentration by half. The $\EC$ is a measure of the potency of an oligonucleotide. A more potent oligonucleotide will have a lower $\EC$ value. In mathematical terms the $\EC$ value is defined as
\begin{equation}
\EC = \left(O_t \left|\, \Trel = \frac{\mathrm{Eff}}{2}+\Trelmin \right.\right)  \enspace, \label{eq::EC50}
\end{equation}
where the efficacy (Eff, the maximum decrease in $\Trel$), and the minimum value of $\Trel$ ($\Trelmin$) are defined by
\begin{equation}
\textrm{Eff}=1-\lim_{O_t \to \infty} \Trel =1 - \Trelmin \label{eq:Eff} \enspace.
\end{equation}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Table S1}
\begin{table}[!h]
\caption{Default values for the parameter-space of the ASO model. Concentrations are measured in nM and time in min.}\label{tb::par}
\setlength\extrarowheight{5pt}  %Increases the height of each row
\begin{tabular}{| l | l | r | l |}
\hline
Parameter & Description &Default value & Ref  \\
\hline
$E_t$ & Total RNAse H concentration & 1 nM & Ref. \cite{Amirkhanov:2002vo}\\
$O_t$ & Total oligonucleotide conc & $\mathcal{O}(\mu M )$ & {}\\
$v_{prod}$ & Production of target & 0.2 nM/min & Ref. \cite{lodish2008molecular}\\
$\vd$ & Degradation of target & 0.04 $\rm{min}^{-1}$ & Ref. \cite{Yang:2003ja}\\
$K_{dOT}$ & Dissociation constant of $OT$ & 0.3 nM & Ref. \cite{Christensen:2001te} \\
$K_{dOTE}$ & Dissociation constant of $OTE$  & 70 nM & Ref. \cite{Amirkhanov:2002vo} \\
$k_{O+T \to OT }$ & Rate of $O+T \to OT$ & $0.2 \, (\rm{nM \,min})^{-1}$ & Ref. \cite{Christensen:2001te}\\
$k_{OT+E \to OTE}$ & Rate of $OT+E \to OTE$  & 5 $(\rm{nM \,min})^{-1}$ & Ref. \cite{Amirkhanov:2002vo}\\
$k_{OTE \to OCE}$ & Rate of cleavage  & 8 $\rm{min}^{-1}$ & Ref. \cite{Amirkhanov:2002vo}\\
$\alpha$ & Ratio of $\frac{k_{OT \to O+T}}{k_{\mathrm{*C \to *+C}}} \le 1$ & 0.1  & {}\\
\hline
\end{tabular}
\end{table}
%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S1}
The R-function \texttt{Trel()} calculates $\Trel$ and takes $O_t$ and the set of parameters as input:
<<echo=TRUE>>=
#The parameters are in vector-format
parms <- c(Et = 1,KdOT = 0.3,kOpT = 0.2,KdOTE = 70,kOTpE = 5,	
           vprod = 0.2,kdegrad = 0.04,alpha=0.1,kcleav = 8)
Trel(Ot=1,param=parms)
@
$\Trel$ can be calculated for a range of different oligonucleotide concentrations ($O_t$) and From this a dose-response curve is obtained. Supplementary Figure~\ref{fig::Etot} shows the change in the dose-reponse curve as the parameters vary. These plots are produced using \texttt{plot.doseresponse()}.
%%%% FIGURE
<<S1,echo=FALSE,fig=TRUE,width=7,height=5,include=FALSE>>=
par(mfrow=c(3,3),mar=c(4,4,0.5,0.5))
#### Changing etot
plot.doseresponse('Et',c(5E-2,0.1,100),expression(E[t]),unit=~nM)
#### Changing alpha
plot.doseresponse('alpha',c(1E-3,0.5,0.75),unit='',
  expression(alpha==over(k[OT%->%O+T],k['*'*C %->% '* +'* C])))
#### Changing vt
plot.doseresponse('vprod',c(0.01,1,2),
  expression(v[prod]),unit=~'nM/min')
#### Changing kd
plot.doseresponse('kdegrad',c(1,1/5,1/10,1/50),
  expression(k[T %->% Ø]),unit=~min^-1)
#### Changing D1
plot.doseresponse('KdOT',c(0.01,10,50),
  expression(K[dOT]== over(k[OT %->% O+T],k[O+T %->% OT])),unit=~'nM')
#### Changing k1
plot.doseresponse('kOpT',c(0.001,0.01,1),
  expression(k[O+T %->% OT]),unit=~nM^-1*min^-1)
#### Changing D2
plot.doseresponse('KdOTE',c(1,10,1000),
  expression(K[dOTE]== over(k[OTE %->% OT+E],k[OT+E %->% OTE])),unit=~'nM')
#### Changing k2
plot.doseresponse('kOTpE',c(0.1,0.5,1000),
  expression(k[OT+E %->% OTE]),unit=~nM^-1*min^-1)
#### Changing kE
plot.doseresponse('kcleav',c(1,100,1000),
  expression(k[OTE %->% OCE]),unit=~min^-1)
@
\begin{figure}[!b]
\includegraphics[width=\textwidth]{SuppFile1-S1.pdf}
\caption{Dose-response curves for different values of $E_{t}$, $\alpha$, $\vp$, $\vd$, $K_{dOT}$, $\ko$, $K_{dOTE}$, $\kt$, and $\kE$ (top,left to bottom,right). Black lines correspond to the parameter values listed in Supplementary Table \ref{tb::par}.}\label{fig::Etot}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S2}
Using the R-function \texttt{drm()} from the drc package (v2.3-0) a dose-response curve is fitted to $\Trel$ as a function of $O_t$ to obtain an $\EC$ value. This is calculated through the R-function \texttt{EC50()} that takes $K_{dOT}$ and the set of parameters as input:
<<>>=
EC50(KdOT=0.1,param=parms)
@
A range of $K_{dOT}$ values,the corresponding $\EC$ values can be calculated. These can be fitted to a second order polynomial by using the R-function \texttt{lm()}, see Supplementary Figure S2. 
<<>>==
D1_seq <- 10^seq(-3,3.2,by=0.25)
ECseq <- sapply(D1_seq,EC50)
FitPar <- lm(log10(ECseq) ~ log10(D1_seq) + I(log10(D1_seq)^2))
@
<<S31,echo=FALSE,fig=TRUE,width=4,height=3,include=FALSE>>=
par(mar=c(4.5,4.5,1,1))
plot(D1_seq,ECseq,log='xy',yaxt='n',type='l',xaxt='n',
     xlab=expression(K[dOT]~'(nM)'),ylab=expression(EC[50]~'(nM)'))
axis(2,at=c(2,20,200),labels=c(2,20,200),las=2)
axis(1,at=10^pretty(log10(D1_seq)),
     labels=pretty10expLP(10^pretty(log10(D1_seq)),drop.1=T),)
Parfun <- function(D1){
  tmp <- coefficients(FitPar) 
  10^(tmp[1]+tmp[2]*log10(D1)+tmp[3]*log10(D1)^2)}
lines(D1_seq,Parfun(D1_seq), col='red')
f <- summary(FitPar)$fstatistic
p <- pf(f[1],f[2],f[3],lower.tail=F)
legend('top',legend=paste('p-value =',signif(p,2)),bty='n')
legend('bottomright',c('model','fit'),col=c('black','red'),lwd=2,bty='n')
@
\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=0.6\textwidth]{SuppFile1-S31.pdf}
\end{Ncenter}
\caption{$\EC$ as a function of $\kdOT$ is fitted on a log-log scale.}\label{fig::Opt}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S3}
Supplementary Figure~\ref{fig::Opt} shows $\EC$ as a function of $K_{dOT}$ for various parameter values. It can be seen that the optimum affinity, quantified by $K_{dOT}$, changes as parameters are changed. A lower value of $K_{dOT}$ correponds to a better affinity for the oligonucleotide.
% % % %
% <<S2,echo=FALSE,fig=TRUE,include=FALSE,width=7,height=4>>=
% parc <- c('Et','alpha','vprod','KdOTE','kcleav','kdegrad')
% xlabl <- list(~nM,~phantom(0),~'nM/min',~nM,'/min','/min')
% xlabll <- list(~E[t],~alpha,~v[prod],~K[dOTE],~k[OTE%->%OCE],~k[T%->% Ø])
% parRange <- list(etot=c(0.01,1,10),alpha=c(0.005,0.01,0.95),
%                   vt=c(0.001,0.01,1.5),D2=c(0.5,10,100),
%                  kE=c(5,100,200),kd=c(0.005,0.05,0.5)) 
% D1_seq <- 10^seq(-3,3,by=0.25)
% EC50_fit <- as.list(1:length(parc))
% for(j in 1:length(parc)){
%  Lparseq <- parRange[[j]]
%  EC50_fit[[j]] <- matrix(NA, nrow=length(Lparseq),ncol=length(D1_seq))
%  
%  for(i in 1:length(Lparseq)){
%    parmsb <- parms; parmsb[parc[j]] <- Lparseq[i]
%    EC50_fit[[j]][i,] <- sapply(D1_seq,EC50,param=parmsb)
%  }
% }
% cbar <- c('orange','darkgreen','black')
% pdf('SuppFile1-S2.pdf',width=6.5,height=6.5)
% layout(matrix(c(1:6),3,2,byrow=T))
% for(j in 1:6){
%  Lparseq <- parRange[[j]]
% 
%  par(cex=0.75,mar=c(4,4,0.5,0.5),bty='o',mgp=c(2.2,0.7,0))
%  
%  for(i in 1:length(Lparseq)){
%    if(i==1){
%      plot(D1_seq,EC50_fit[[j]][1,],log='xy',panel.first=grid(col='grey',lty=3),
%            ylab=expression(EC[50]~' (nM)'),col=cbar[i],
%            ylim=c(1E-1,200),type='l',xaxt='n',yaxt='n',lwd=2,xlab=expression(K[dOT]~'(nM)'))
%      axis(1,at=c(1E-2,1,1E2),labels=pretty10expLP(10^c(-2,0,2),drop.1=T))
%      axis(2,at=c(1E-1,1,10,1E2),labels=pretty10expLP(10^c(-1:2),drop.1=T))
%    }else{
%      lines(D1_seq,EC50_fit[[j]][i,],col=cbar[i],lwd=2)
%     }
%   }
%   legend('bottomright',fill=cbar,cex=0.65,bg='white',x.intersp=0.2,
%           legend=as.expression(sapply(Lparseq,
%                            function(x) substitute(x*y,list(x=x,y=xlabl[[j]])))),
%           border=cbar,bty='o',box.lwd=0.5)
%   legend('top',as.expression(xlabll[[j]]),bty='n')
% }
% dev.off()
% % % @
% % 

\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=\textwidth]{SuppFile1-S2.pdf}
\end{Ncenter}
\caption{The optimum affinity is dependent on the parameter settings. In the panels the $\EC$ concentration is plotted against the binding affinity quantified by $K_{dOT}$ for various parameters. We have varied the total RNAse H concentration ($E_t$), alpha, the rate of target cleavage ($k_{OTE \to OCE}$), the target production ($v_{prod}$) and degradation ($\vd$), and the dissociation constant for the OTE complex ($K_{dOTE}$).}\label{fig::Opt}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S4}
The stochastic simulation of the ASOmodel is carried out by use of the \texttt{ssa()} R-function from the GillespieSSA package (v.0.5-4). The inputs to ssa are an initial state vector (x0), which is the initial number of molecules, a propensity vector (a), which denotes the different states of the system, a state-change matrix (nu), which is the change in number of molecule (rows) if a reaction occur (column), the model-parameters (parms) and the final time (tf).
<<echo=T>>=
library(GillespieSSA)
#Model parameters
parms1 <- c(kOpT = 2E-5,kOTpE =50E-5 ,vprod = 150,  kdegrad = 0.04,		  
              kcleav = 2, kOT =0.06, kOTE=2, kC = 0.1)
#Initital state vector
x0 <- c(Tt=parms1["vprod"]/parms1["kdegrad"],
        OT=0,OTE=0,E=1e3,O=1e5,OCE=0,OC=0)
names(x0) <- c('Tt','OT','OTE','E','O','OCE','OC')
#Propensity vector
a <-  c("vprod","kOpT*O*Tt","kdegrad*Tt","kOT*OT","kOTE*OTE","kdegrad*OT",
        "kOTpE*OT*E","kdegrad*OTE","kcleav*OTE","kC*OC","kOTE*OCE" )
#State-change matrix
nu <- matrix(0,7,length(a))
dimnames(nu) <- list(names(x0),a)
#T
nu['Tt',c('vprod','kOT*OT')] <- 1
nu['Tt',c('kOpT*O*Tt','kdegrad*Tt')] <- -1 
#OT
nu['OT',c('kOpT*O*Tt','kOTE*OTE')] <- 1
nu['OT',c('kOT*OT','kOTpE*OT*E','kdegrad*OT')] <- -1
#OTE
nu['OTE',c('kOTpE*OT*E')] <- 1
nu['OTE',c('kOTE*OTE','kdegrad*OTE','kcleav*OTE')] <- -1
#E
nu['E',c('kOTE*OTE','kdegrad*OTE','kOTE*OCE')] <- 1
nu['E',c('kOTpE*OT*E')] <- -1
#O
nu['O',c('kOT*OT','kdegrad*OTE','kdegrad*OT','kC*OC')] <- 1
nu['O',c('kOpT*O*Tt')] <- -1
#OCE
nu['OCE',c('kcleav*OTE')] <- 1
nu['OCE',c('kOTE*OCE')] <- -1
#OC
nu['OC',c('kOTE*OCE')] <- 1
nu['OC',c('kC*OC')] <- -1

Gillespie <- ssa( x0=x0,a=a,nu=nu,
      parms = parms1,tf=1E3,method = "ETL")
@
% Check that $[O]+[OT]+[OTE]+[OCE]+[OC] = O_t$ at all times:
% <<echo=T>>=
% range(rowSums(Gillespie$data[,c('O','OT','OTE','OCE','OC')])-
%         x0['O'])
% @
% Check that $[E]+[OTE]+[OCE] = E_t$ at all times:
% <<echo=T>>=
% range(rowSums(Gillespie$data[,c('OTE','OCE','E')])-x0['E'])
% @
<<Trel,echo=F,fig=TRUE,width=5,height=4,include=FALSE>>=
# plot of the time-trase for Trel
par(mar=c(4.5,4.5,1,1))
plot(Gillespie$data[,1],rowSums(Gillespie$data[,2:4])/(parms1["vprod"]/parms1["kdegrad"]),
		xlab='time (min)',ylab='Relative total target level',type='l')
@
Supplementary Figure~\ref{fig:Trelstoc} shows $\Trel$ from the Gillespie simulation.
\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=0.6\textwidth]{SuppFile1-Trel.pdf}
\end{Ncenter}
\caption{The time-trace for the relative total target level when the ASO model is simulated stochastically.}\label{fig:Trelstoc}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S5}
After a while the stochastic simulation reaches a plateau. In Supplementary Figure~\ref{fig:Trelstoc} the plateu starts around $50$min. The mean of $\Trel$ within the plateu is calculated through the R-function \texttt{Trelstoc()}. Using this function we can generate dose-response curves (Supplementary Figure~\ref{fig:stocEC50},left). From these $\EC$ values can be calculated using \texttt{EC50stoc()} and they are subsequently plotted as a function of $\kmo$ (Supplementary Figure~\ref{fig:stocEC50},right):
<<echo=T>>=
#### Sequence of k(OT -> O+T) values
lseq <- c(1,2.5,5,7.5)
lKOT <- c(1E-3*lseq[-1],1E-2*lseq,1E-1*lseq)
#### Generation of dose-response curves
DRcurve <- lapply(lKOT,function(ki){ 
            sapply(10^seq(2.5,6,by=0.2),
                   function(i) Trelstoc(i,kOT=ki)$Tstat)})
DRc <- lapply(DRcurve,function(x) x[,!is.na(x[3,])] )
#### Calculation of EC50
EC50_lKOT <- sapply(1:length(DRc),
              function(x){EC50stoc(DRc[[x]][2,],DRc[[x]][1,])})
@
<<EC50,echo=F,fig=TRUE,width=7,height=4,include=FALSE>>=
par(mfcol=c(1,2),mar=c(4,4.5,1,1),mgp=c(2.5,0.7,0))
N <- length(DRc)
plot(DRc[[1]][1,],DRc[[1]][2,],ylab='Relative target level',ylim=c(0,1),
		xlab='Total oligonucleotide (molecules)',log='x',type='l',
		col=rainbow(N)[1],xlim=c(2E3,max(unlist(DRc))),lwd=2)
LegendS=as.expression(sapply(signif(lKOT[seq(1,11,by=2)],2),
                function(x) substitute(y==x,list(x=x,y=~k[OT %->% O+T]))))
legend('bottomleft',LegendS,#signif(KM[seq(1,11,by=2)],2)),
		col=rainbow(N)[seq(1,11,by=2)],lwd=2,bty='n',cex=0.6)
for(i in seq(3,11,by=2)){
	points(DRc[[i]][1,],DRc[[i]][2,],col=rainbow(N)[i],type='l',lwd=2)
}

plot(lKOT,EC50_lKOT,log='x',ylab=expression(EC[50]~'(molecules)'),
		xlab=expression(k['OT'%->%'O+T']~'(1/min)'))
@
\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=\textwidth]{SuppFile1-EC50.pdf}
\end{Ncenter}
\caption{Left: Dose-response curves for various values of $\kmo$ (compare to Supplementary Figure S1,middle). Right: $\EC$ as a function of $\kmo$.}\label{fig:stocEC50}
\end{figure}
\newpage


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S6}
\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=0.65\textwidth]{SuppFig_PS.pdf}
\end{Ncenter}
\caption{The effect on $T_m$ of a phosphorothioate backbone was estimated using published data from Ref. \cite{Hashem:1998kf}.}\label{fig:figPS}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Supplementary Figure S7}
\begin{figure}[!h]
\begin{Ncenter}
\includegraphics[width=\textwidth]{SuppFigS3.pdf}
\end{Ncenter}
\caption{Measured melting temperature versus predicted melting temperature. There are clear correlations (r > 0.92, P < 0.01, Pearson's correlation) between predicted and measured $T_m$. Pedersen et al: 4 LNA-modified oligonucleotides targeting apolipoprotein B (this work), Stanton et al: 14 LNA-modified oligonucleotides targeting the glucocorticoid receptor \cite{Stanton:2012fu}. Frieden et al: 21 LNA-modified oligonucleotides targeting the luciferase firefly gene \cite{Frieden:2003er}.\\
Melting curves were recorded with a Perkin Elmer spectrophotometer. Oligonucleotide and its complementary RNA, both at 1.5$\mu M$, were dissolved in buffer (20mM phosphate buffer, 100mM NaCl, 0.1nM EDTA, pH 7). Samples were denatured at 95$^\circ$C for 3min and slowly cooled to 20$^\circ$C prior to measurements. Melting curves were recorded at 260nm using a heating rate of 1$^\circ$C/min, a slit of 2nm and a response of 0.2s. From this, $T_m$ values were obtained from the maxima of the first derivatives of the melting curves.}\label{fig:figTm}
\end{figure}

\newpage
\bibliography{ASOmodels}


\end{document}